### ISSUE TITLE
Linking CXX shared library libGreenIslandPlatform (Threads::Threads)

### ISSUE THREAD

**Issue by hackdefendr** [greenisland/greenisland#124]
I have no idea where to get Threads::Threads package. GreenislandPlatform won't build without it. I have tried installed every threads related development package and still no go. I tried installing threads via cpan and still no go. I tried forcing it to non-ALIAS, and the cmake process finds package Threads, but still fails...here is the crash message:

`Linking CXX shared library libGreenIslandPlatform.so
/usr/bin/ld: cannot find -lThreads::Threads
collect2: error: ld returned 1 exit status
src/platform/CMakeFiles/GreenIslandPlatform.dir/build.make:650: recipe for target 'src/platform/libGreenIslandPlatform.so.0.6.92' failed
make[2]: *** [src/platform/libGreenIslandPlatform.so.0.6.92] Error 1
CMakeFiles/Makefile2:934: recipe for target 'src/platform/CMakeFiles/GreenIslandPlatform.dir/all' failed
make[1]: *** [src/platform/CMakeFiles/GreenIslandPlatform.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2`

Can someone please tell me how to fix this?

**Comment by hackdefendr** [comment]
Ok

I hacked and hacked and hacked and finally got it working. Install pthread development package.

**Changes required**

Copy some cmake modules into cmake sub-folder:

`cp /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake cmake/
cp /usr/share/cmake-3.0/Modules/FindPackageMessage.cmake cmake/
cp /usr/share/cmake-3.0/Modules/CMakeParseArguments.cmake cmake/`

Edit file ./src/platform/CMakeLists.txt:

*LINE 20*
`set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH} ${ECM_KDE_MODULE_DIR} "${CMAKE_SOURCE_DIR}/cmake")`

*LINE 80*
change Threads::Threads
to pthread

**Run cmake from build sub-folder like normal**

**Comment by plfiorini** [comment]
What distro are you running?

**Comment by hackdefendr** [comment]
Kali Linux v2 (Essentially Debian 7/8)

**Comment by plfiorini** [comment]
Ok thanks, I will try to investigate whether I need to do something here upstream or not.
FindThreads.cmake is shipped by cmake itself and all the mentioned cmake files too so I'm a bit surprised it didn't work OOB.
