### ISSUE TITLE
Maximized Gtk windows are offset

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#157]
When I maximize a Gtk window, the window is offset. I'm guessing this is because of padding around the window decorations for the shadow.

Here's a screenshot from the sample shell:

![screenshot from 2015-12-24 15-22-07](https://cloud.githubusercontent.com/assets/3230912/11997995/7e592efc-aa52-11e5-9ba6-504ae1e53f48.png)

**Comment by plfiorini** [comment]
Done
