### ISSUE TITLE
Modifier keys are not passed to applications

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#158]
**Steps to Reproduce**

1. Open a Gtk or Qt application (I've tried Files and Dolphin) in the sample compositor
2. Type a keyboard shortcut such as `Ctrl+L`
3. In Files, the quick filter bar is opened with `L` entered in the text field
4. In Dolphin, the first file starting with `L` is selected

**What should happen**

I expect that the modifier key (in this case, `Ctrl`) is passed to the application allong with any other keys I press.

**Comment by iBeliever** [comment]
After futher testing, I've realized this bug is worse than I thought and makes Green Island practically unusable at the moment, because not only does it not pass Ctrl/Alt/etc to applications, but it doesn't pass Shift, so everything is in lower case and none of the symbols above the number keys work.

Using a test Qt program, I've found that when you press Ctrl/Alt/shift/Super/etc, the key is passed to the program, but once you press another key, the original key is not passed as a modifier.

Here's the test program I used:

    import QtQuick 2.4

    Item {
        width: 100
        height: width

        Component.onCompleted: forceActiveFocus()

        Keys.onPressed: {
            print(event.modifiers, event.key, event.text)
        }
    }

**Comment by VirusKA** [comment]
@plfiorini?

**Comment by plfiorini** [comment]
You need Qt 5.6 which has the QWindowSystemEventHandler.

**Comment by plfiorini** [comment]
There's also a problem with Wayland clients that is being fixed with Qt 5.6 that prevented modifiers from working like Ctrl on Konsole.

**Comment by VirusKA** [comment]
nice Qt 5.6 is coming out in three days (hopefully)
