### ISSUE TITLE
After using the compositor for a while, I lost mouse input

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#159]
When I try to interact with the compositor, I see:

    Cannot send touch event, no pointer focus, fix the compositor

This is with the sample compositor, but I've been able to reproduce this in Papyros shell as well.

**Comment by plfiorini** [comment]
Yep this is a bug in the current QtCompositor API, should be fixed with the new QWaylandCompositor API that I'm slowly integrating.
