### ISSUE TITLE
Applications occasionally close due to a Wayland error

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#163]
This happens under a variety of circumstances. It doesn't seem to be triggered by user input. Often it happens when the app is first opened. This is the error the application shows:

    The Wayland connection experienced a fatal error (Value too large for defined data type)

I'm not sure what other logs would be helpful. I can reproduce this error often enough that I can get whatever logs you would find useful.

**Comment by plfiorini** [comment]
That looks like a bug of QtCompositor, we'll see what happens with QtWaylandCompositor.
Closing for now.
