### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by alihanozturk** [greenisland/greenisland#212]
42%] Linking CXX shared library libGreenIslandPlatform.so
[ 42%] Building CXX object src/client/CMakeFiles/GreenIslandClient.dir/GreenIslandClient_automoc.cpp.o
[ 43%] Building CXX object src/waylandcompositor/CMakeFiles/GreenIslandCompositor.dir/extensions/qwaylandtextinputmanager.cpp.o
/usr/bin/ld: error in /usr/lib/libQt5PlatformSupport.a(qfontconfigdatabase.o)(.eh_frame); no .eh_frame_hdr table will be created.
collect2: error: ld returned 1 exit status
src/platform/CMakeFiles/GreenIslandPlatform.dir/build.make:865: recipe for target 'src/platform/libGreenIslandPlatform.so.0.7.91' failed
make[2]: *** [src/platform/libGreenIslandPlatform.so.0.7.91] Error 1
CMakeFiles/Makefile2:1509: recipe for target 'src/platform/CMakeFiles/GreenIslandPlatform.dir/all' failed
make[1]: *** [src/platform/CMakeFiles/GreenIslandPlatform.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by plfiorini** [comment]
Could you give some details like distro, gcc version, binutils version, Qt version.
This look like something weird going on with binutils.

**Comment by alihanozturk** [comment]
I use Pisilinux. 
gcc, sürüm: 5.3.0
binutils, sürüm: 2.26
qt5-base, sürüm: 5.6.0,

**Comment by plfiorini** [comment]
Possibly this ld bug here: https://lists.gnu.org/archive/html/bug-binutils/2016-03/msg00185.html
Probably Pisilinux hasn't picked up the fix yet.

**Comment by plfiorini** [comment]
I'm closing the issue as invalid as it appears a bug in ld.
The code has been built on other distros for example Arch, Fedora 23, 24 and rawhide without problems.
