### ISSUE TITLE
Support for Google Cardboard VR

### ISSUE THREAD

**Issue by HokeyPokeyStar** [greenisland/greenisland#213]
Can we have an app which can be installed on a phone which shows the Greenisland desktop using Google Cardboard.It would be quite cool if we could have this and the next Linux distro might be a VR one ;)

I have seen this already done here : https://github.com/evil0sheep/motorcar

**Comment by plfiorini** [comment]
Now you got me curious :D

**Comment by SuicSoft** [comment]
@plfiorini I accidently posted from another account I have.So I actually posted it.

And it is a nice idea and Linux will be ahead of Windows if it happens

**Comment by SuicSoft** [comment]
@plfiorini New issue link #214

**Comment by SuicSoft** [comment]
@plfiorini Remember to move you comments (I can move mine)
