### ISSUE TITLE
[LiveCD] Starting Hawaii on i5

### ISSUE THREAD

**Issue by STiAT** [greenisland/greenisland#30]
Hi,

I've wanted to try and check the project a bit using the LiveCD (botting it from a USB Stick), to see if it's fun :).
So I did, but running the /root/start.sh I get the following output:
[drm: __gen6_gt_force_wake_get] *ERROR* Timed out waiting for forcewake to ack request.
[drm: __gen6_gt_wait_for_thread_c9] *ERROR* GT thread status wait timed out

That's all. After that ouput, my keyboard does not react any longer, I can't switch to other consoles to get something like a dmesg output. Only thing I can do is a hard reset.
Any ideas?

**Comment by plfiorini** [comment]
Qt 5.5 will finally have KMS hooks for eglfs as a replacement to the broken qkms plugin (no logind support yet though, which means one has to run the compositor as root).
Reminder: test this on several configurations after the Qt 5.5 release.

**Comment by plfiorini** [comment]
Closing because this doesn't apply anymore since the compositor can be nested into Weston (or use KMS with Qt 5.5).
