### ISSUE TITLE
Greenisland fails to compile

### ISSUE THREAD

**Issue by n3rdopolis** [greenisland/greenisland#51]
I am using qtwayland dev branch now that qwaylandoutput was merged, and greenisland master. I thought it built earlier though, so I don't know why I am getting a build fail...

[ 38%] [ 40%] [ 42%] [ 42%] Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/applicationmanager.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/clientwindow.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/globalregistry.cpp.o
[ 44%] Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/gldebug.cpp.o
[ 45%] Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/homeapplication.cpp.o
/srcbuild/greenisland/src/libgreenisland/compositor.cpp: In member function ‘virtual QWaylandSurfaceView* GreenIsland::Compositor::pickView(const QPointF&) const’:
/srcbuild/greenisland/src/libgreenisland/compositor.cpp:319:52: error: ‘class QWaylandOutput’ has no member named ‘surfaces’
             for (QWaylandSurface *surface: output->surfaces()) {
                                                    ^
src/libgreenisland/CMakeFiles/GreenIsland.dir/build.make:204: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o' failed
make[2]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:425: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/all' failed
make[1]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
PackageCompileSource finished in 14 seconds

**Comment by schnitzeltony** [comment]
On Fri, Feb 13, 2015 at 4:32 AM, n3rdopolis <notifications@github.com>
wrote:

> I am using qtwayland dev branch now that qwaylandoutput was merged, and
> greenisland master. I thought it built earlier though, so I don't know why
> I am getting a build fail...
>
> [ 38%] [ 40%] [ 42%] [ 42%] Building CXX object
> src/libgreenisland/CMakeFiles/GreenIsland.dir/applicationmanager.cpp.o
> Building CXX object
> src/libgreenisland/CMakeFiles/GreenIsland.dir/clientwindow.cpp.o
> Building CXX object
> src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o
> Building CXX object
> src/libgreenisland/CMakeFiles/GreenIsland.dir/globalregistry.cpp.o
> [ 44%] Building CXX object
> src/libgreenisland/CMakeFiles/GreenIsland.dir/gldebug.cpp.o
> [ 45%] Building CXX object
> src/libgreenisland/CMakeFiles/GreenIsland.dir/homeapplication.cpp.o
> /srcbuild/greenisland/src/libgreenisland/compositor.cpp: In member
> function ‘virtual QWaylandSurfaceView*
> GreenIsland::Compositor::pickView(const QPointF&) const’:
> /srcbuild/greenisland/src/libgreenisland/compositor.cpp:319:52: error:
> ‘class QWaylandOutput’ has no member named ‘surfaces’
> for (QWaylandSurface
>
>
> *surface: output->surfaces()) { ^
> src/libgreenisland/CMakeFiles/GreenIsland.dir/build.make:204: recipe for
> target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o'
> failed make[2]: ***
> [src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:425: recipe for target
> 'src/libgreenisland/CMakeFiles/GreenIsland.dir/all' failed
> make[1]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/all] Error 2
> Makefile:147: recipe for target 'all' failed
> make: *** [all] Error 2
> PackageCompileSource finished in 14 seconds
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenisland/greenisland/issues/51>.
>
You have to use a tailored (patches not yet applied upstream) qtwayland as
mentioned in README.md

Andreas

**Comment by plfiorini** [comment]
Yes Andreas is right.
Only the first patch was merged upstream, the second one is under review and hopefully will land soon.
