### ISSUE TITLE
Green Island fails to load with the fullscreen shell option

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#62]
Weston doesn't load the Green Island compositor:

	$ greenisland-launcher --fullscreen-shell -p org.greenisland.simple
	QML debugging is enabled. Only use this in a safe environment.

	Using Wayland-EGL

	Compositor ready, notify systemd on ""

	Launcher finished with exit code 11 , status 1

![weston compositor](https://cloud.githubusercontent.com/assets/3230912/6548843/4f1222ec-c5d4-11e4-8c3d-e8259d3a998d.png)

Also, trying to log in to Hawaii desktop results in a black screen with a blinking text cursor in the corner. I'm guessing it's the same problem.

This is on a fully up-to-date Arch Linux system (x86_64 architecture, MacBook Pro 2013), with Weston v1.7.0. Weston loads correctly on its own, both inside GNOME Shell and as a login session from GDM. I built a new version of Green Island tonight. I'm not sure if this is an issue with Green Island, the version of Weston I have, or some other local issue, but I'd appreciate any help you can give getting it working.

**Comment by plfiorini** [comment]
I'm on it, I have an idea on what might be happening.
