### ISSUE TITLE
Provide model of open windows and applications

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#64]
It would be nice to have this in GreenIsland so individual desktop shells don't have to implement it. This could probably be moved from the existing application model code in Hawaii: https://github.com/hawaii-desktop/hawaii-shell/tree/master/declarative/launcher.

**Comment by iBeliever** [comment]
@plfiorini Any thoughts on this?

**Comment by plfiorini** [comment]
There's already the ApplicationManager object for that, you can easily implement a model that suits your needs with it.  Such a high level component doesn't need to be in a compositor.
Once you have a model with running applications you want to show only applications for the current screen or the current workspace but workspaces are not currently handled as they are an implementation detail, then you realize that it will be used by a launcher and so you need to offer features such as pin/unpin, run etc...

**Comment by iBeliever** [comment]
Thanks for the response! You're right, the ApplicationManager class was quite sufficient, and looking at how Hawaii implemented the app panel was quite helpful as well. Thanks!
