### ISSUE TITLE
Green Island window is partially offscreen when running in GNOME Shell

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#75]
When I run Green Island (using `green island --shell io.papyros.shell`), the window content is the size of the physical display. However, when running inside GNOME Shell, the window content is offset is offset by the height of the window titlebar and the system status bar, resulting in the bottom of the compositor being hidden offscreen, with no way to access it.

Would it be possible to default to using fake screen data when launched within an existing desktop environment, so the window is maximized without going offscreen? I know there's a command-line argument for using fake screen data, but it seems like this is a common enough issue that it would be nice to automatically handle it in Green Island.

**Comment by plfiorini** [comment]
Yes seems like a good idea
