### ISSUE TITLE
Use a WindowManager component to share code between compositors

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#77]
Just about every compositor is going to need some common code related to window management. The code in your WindowManagement.js file, along with the window wrapper, effects code, and workspace management, is common enough that probably every compositor will be doing something similar.

So, this seems like an ideal piece of functionality to abstract out at put in Green Island. What I propose is the following:

 * A WindowManager type that handles listening to Green Island and creating and destroying window instances as necessary
 * This WindowManager would have three Component properties for the different types of windows. These properties would be used by the window manager when Green Island notifies it of new windows.
 * It would also manage a ListModel of workspaces, which each compositor could use in its own way to display the workspaces (for example, in a grid or listview).
 * This window manager would also provide hooks for adding effects, along with a base effect class.
 * Provide a base WindowWrapper class that can be used by different compositors to provide their own animations and effects (and possibly decorations, not sure if this can be done in QML).
 * This WindowManager could also be used to expose a model of application objects (not just windows), for the entire window manager and also on a per-workspace level (see #64).

If this proposal sounds good to you, I'd be happy to implement a first-pass of it and submit a pull request.

**Comment by plfiorini** [comment]
Makes sense, I'm thinking about how to do this.
I just wanted to tell you that I've seen this and I'll get on this once dealt with #70

**Comment by plfiorini** [comment]
There's a window manager component now.
