### ISSUE TITLE
Windows maximize to the full size of the screen

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#82]
Windows should instead maximize to the size of their parent view, so they fit properly between system panels.

Maybe the solution to this is to handle maximizing in QML, like minimizing is?

**Comment by plfiorini** [comment]
Per output available geometry is set from QML using panels position and size, which means that C++ will be automatically notified when the available geometry changes.

**Comment by iBeliever** [comment]
Thanks for pointing me in the right direction, that was exactly what I needed.
