### ISSUE TITLE
Segmentation fault when quiting the compositor

### ISSUE THREAD

**Issue by iBeliever** [greenisland/greenisland#92]
Running the latest code from `master` and calling `Compositor.abortSession()` from a mouse area in the sample compositor results in the compositor segfaulting.

See the logs and backtrace [here](https://gist.github.com/iBeliever/78eda3cdef77b3f63a9b).

**Comment by plfiorini** [comment]
Investigating...

**Comment by plfiorini** [comment]
How do you quit greenisland?

**Comment by iBeliever** [comment]
This is still not fixed. Looks like QScreen doesn't like being called during the compositor shutdown. Here are [more gdb logs](https://gist.github.com/iBeliever/0837d1f8ec6d4ec6f7cb). Can you please reopen the issue?

**Comment by plfiorini** [comment]
Good catch I was testing only with the fake screen backend

**Comment by plfiorini** [comment]
Does this still happen?
